# Generated by Django 2.2.5 on 2020-03-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anunciante', models.CharField(max_length=150, unique=True, verbose_name='Nome do anunciante')),
                ('apresentacao', models.TextField(verbose_name='Apresentação')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('slug', models.SlugField(verbose_name='URL anúncio')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque?')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('logo_categoria', models.ImageField(upload_to='anuncios/logo_categoria')),
                ('slug', models.SlugField(default='', verbose_name='url')),
                ('tipo', models.IntegerField(choices=[(1, 'Negócio'), (2, 'Classificado')], verbose_name='Tipo de categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FotoAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='anuncios/foto_anuncio')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('banner', models.BooleanField(default=False, verbose_name='Banner')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='anuncio.Anuncio')),
            ],
            options={
                'verbose_name': 'Foto do anúncio',
                'verbose_name_plural': 'Fotos dos anúncios',
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncio.Categoria'),
        ),
    ]
