# Generated by Django 2.2.5 on 2020-04-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.IntegerField(choices=[(None, 'Selecione...'), (1, 'Negócio'), (2, 'Classificado')], default=None, verbose_name='Tipo de categoria'),
        ),
    ]
