# Generated by Django 2.2.5 on 2020-04-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_auto_20200421_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anunciante',
            options={'ordering': ['nome'], 'verbose_name': 'Anunciante', 'verbose_name_plural': 'Anunciantes'},
        ),
        migrations.AlterField(
            model_name='anunciante',
            name='cep',
            field=models.CharField(max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='anunciante',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ'),
        ),
    ]
