# Generated by Django 2.2.5 on 2020-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
